alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias l='ls'
alias ll='ls -l'
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias sass='sass --unix-newlines --watch --style expanded'
alias scss='scss --unix-newlines --watch --style expanded'
alias crs='cd ~/Desktop/Spectator/courses'
alias shft='cd ~/Desktop/Spectator/the-shaft'
alias redis='redis-server'
alias postgres='postgres -D /usr/local/var/postgres'
alias esearch='elasticsearch --config=/usr/local/opt/elasticsearch/config/elasticsearch.yml'
alias rs='rails s'
alias rc='rails c'
alias sem='cd ~/Desktop/Spring\ 2016/'
alias clic='ssh -X ak3688@clic.cs.columbia.edu'
alias cdd='cd ~/Desktop'
